### PR TITLE
VPN-5492: Some elements in 'Select Location' screen are not read by screen reader

### PR DESCRIPTION
**Pull request by vinocher**
## Description

Some elements in the 'Select Location' screen did not have the correct Accessible names.

## Reference

[VPN-5492](https://mozilla-hub.atlassian.net/browse/VPN-5492), [GitHub 7952](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/7952)

## Checklist
    
- [x] My code follows the style guidelines for this project
- [x] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [x] I have performed a self review of my own code
- [x] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

[VPN-5492]: https://mozilla-hub.atlassian.net/browse/VPN-5492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Gela — APPROVED** [review]

**Review by MattLichtenstein — CHANGES_REQUESTED** [review]
When accessing the multi-hop view, but still being set to single-hop, the entry server city name is not read out. It works fine if multi-hop is enabled. My guess is that there is no Entry server set when we are set to single-hop

setting `descriptionText: segmentedNav.multiHopEntryServer[2]` would likely do the trick (as that is what is used for the actual label text)... not sure why though since it is bound to the same property (`VPNCurrentServer.localizedEntryCityName`) - probably something to do with binding updates

**Comment by vinocher** [comment]
> When accessing the multi-hop view, but still being set to single-hop, the entry server city name is not read out. It works fine if multi-hop is enabled. My guess is that there is no Entry server set when we are set to single-hop
> 
> setting `descriptionText: segmentedNav.multiHopEntryServer[2]` would likely do the trick (as that is what is used for the actual label text)... not sure why though since it is bound to the same property (`VPNCurrentServer.localizedEntryCityName`) - probably something to do with binding updates

Good catch! Yes, It looks like this occurs because multiHopEntryServer is set in ViewServers.qml when the user switches to the multi-hop view, and VPNCurrentServer.localizedEntryCityName  has not been set yet. Replaced the etnry server's descriptionText with multiHopEntryServer[2]. Also changed the exist server's descriptionText to multiHopExitServer[2] for consistency.

**Comment by MattLichtenstein** [comment]
> > When accessing the multi-hop view, but still being set to single-hop, the entry server city name is not read out. It works fine if multi-hop is enabled. My guess is that there is no Entry server set when we are set to single-hop
> > setting `descriptionText: segmentedNav.multiHopEntryServer[2]` would likely do the trick (as that is what is used for the actual label text)... not sure why though since it is bound to the same property (`VPNCurrentServer.localizedEntryCityName`) - probably something to do with binding updates
> 
> Good catch! Yes, It looks like this occurs because multiHopEntryServer is set in ViewServers.qml when the user switches to the multi-hop view, and VPNCurrentServer.localizedEntryCityName has not been set yet. Replaced the entry server's descriptionText with multiHopEntryServer[2]. Also changed the exist server's descriptionText to multiHopExitServer[2] for consistency.

Yep, so from my understanding this definition in `ViewServers.qml` isn't actually ever useful:

`property var multiHopEntryServer: [VPNCurrentServer.entryCountryCode, VPNCurrentServer.entryCityName, VPNCurrentServer.localizedEntryCityName]`

Maybe we just define it to be an empty list `property var multiHopEntryServer: []` since we never use the default value

would also need to change [this line](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/3206e02e69e43eb0c556a8ca0335ca0d558fe5ab/src/ui/screens/home/ViewServers.qml#L112) to check for `multiHopEntryServer.length === 0`

what do you think?

**Comment by vinocher** [comment]
> > > When accessing the multi-hop view, but still being set to single-hop, the entry server city name is not read out. It works fine if multi-hop is enabled. My guess is that there is no Entry server set when we are set to single-hop
> > > setting `descriptionText: segmentedNav.multiHopEntryServer[2]` would likely do the trick (as that is what is used for the actual label text)... not sure why though since it is bound to the same property (`VPNCurrentServer.localizedEntryCityName`) - probably something to do with binding updates
> > 
> > 
> > Good catch! Yes, It looks like this occurs because multiHopEntryServer is set in ViewServers.qml when the user switches to the multi-hop view, and VPNCurrentServer.localizedEntryCityName has not been set yet. Replaced the entry server's descriptionText with multiHopEntryServer[2]. Also changed the exist server's descriptionText to multiHopExitServer[2] for consistency.
> 
> Yep, so from my understanding this definition in `ViewServers.qml` isn't actually ever useful:
> 
> `property var multiHopEntryServer: [VPNCurrentServer.entryCountryCode, VPNCurrentServer.entryCityName, VPNCurrentServer.localizedEntryCityName]`
> 
> Maybe we just define it to be an empty list `property var multiHopEntryServer: []` since we never use the default value
> 
> would also need to change [this line](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/3206e02e69e43eb0c556a8ca0335ca0d558fe5ab/src/ui/screens/home/ViewServers.qml#L112) to check for `multiHopEntryServer.length === 0`
> 
> what do you think?

That would break the case when the user is already in multi-hop and then goes into Select Location's multi-hop view directly, because multiHopEntryServer would not be initialized. It looks like multiHopEntryServer does need to be initialized to handle that case. And `multiHopEntryServer.length === 0` check is needed to handle the case when the user in is single-hop.

**Comment by MattLichtenstein** [comment]
> That would break the case when the user is already in multi-hop and then goes into Select Location's multi-hop view directly, because multiHopEntryServer would not be initialized. It looks like multiHopEntryServer does need to be initialized to handle that case. And the `multiHopEntryServer.length === 0` check is needed to handle the case when the user is in single-hop and goes into Select Location's multi-hop view .

you're totally right. okay, I will settle for a comment above `multiHopEntryServer` declaration stating that these are defined in `handleSegmentClick` if we're not already set to multi-hop

**Review by MattLichtenstein — APPROVED** [review]

**Pull request merged**
