### PR TITLE
VPN-5261 - Bring back the 2.15 whats new message

### PR DESCRIPTION
**Pull request by brizental**
This was deleted by mistake, 2.15 is the current release.

### CODE REVIEW

**Comment by flodolo** [comment]
Do we really need to reintroduce this in `main`? We are not going to update the 2.15.* branch (translations are frozen), so I feel like we're spending community bandwidth unnecessarily.

**Comment by brizental** [comment]
I think this is a limitation on our addon infrastructure. The real fix here I guess would be to have different versions of the application fetch from different addon endpoints. Another option that came up on our meeting today is marking some strings as obsolete i.e. if they are old new langauges added do not need to translate them, but whatever is there stays there. Is that possible @flodolo ?

**Comment by brizental** [comment]
> I might be missing what's the goal by adding these back (what's the behavior of users with or without, etc.)

The issue here is that 2.15 is the latest available version of the VPN and removing these from the main branch means they are not part of the addons RC -- yes, it is built from main :/. So users updating now to 2.15 are not getting this the "What's new" message.

**Review by flodolo — APPROVED** [review]
I'd prefer to keep these untranslated, but I can try to work around it to avoid retranslation if we really need to.

**Pull request merged**
