### PR TITLE
VPN-2705 Users should have a way to opt out of default on data collection even before subscribing.

### PR DESCRIPTION
**Pull request by Gela**
## Description

Users should have a way to opt out of default on data collection even before subscribing. 
This PR adds the same "opt out" checkbox under App Preferences in the pre-login menu.

Screenshot 2023-08-26 at 6 38 22 PM

## Reference

    https://mozilla-hub.atlassian.net/browse/VPN-2705

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

### CODE REVIEW

**Review by MattLichtenstein — CHANGES_REQUESTED** [review]
I agree with the concept of exposing this option pre-authentication, but I think we should get UX involved with what we want that to look like, and where we should put it

**Review by lesleyjanenorton — COMMENTED** [review]
I support providing the opt out prior to authentication and appreciate you driving this forward but I agree with Matt's comments that we should loop in UX for some guidance here.
cc @peterbenvenuto Is this something you have bandwidth to support?

**Comment by peterbenvenuto** [comment]
Hey! Thanks for the tag. I think this would be a good thing to bring up during our next design sync when Santiago is back! If this is somethigg we want to do, it would probably be a feature request and would require some design work + a ticket. Let's being it up next week, thanks!

**Comment by Gela** [comment]
closing this until we finalize a design

**Pull request closed without merging**
