### PR TITLE
Linux: Remove the use of polkit

### PR DESCRIPTION
**Pull request by oskirby**
## Description
It seems that we no longer require the use of `polkit` in the VPN client, the daemon acquires sufficient privileges when launched via systemd, and is granted `CAP_NET_ADMIN` as well during installation. As such, we can simply remove all the code related to polkit from the codebase.

## Checklist
    
- [ ] My code follows the style guidelines for this project
- [ ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ ] I have performed a self review of my own code
- [ ] I have commented my code PARTICULARLY in hard to understand areas
- [ ] I have added thorough tests where needed

### CODE REVIEW

**Review by lesleyjanenorton — APPROVED** [review]
🫳
.
..
...
....
...
..
.
.
.


🎤

**Comment by lesleyjanenorton** [comment]
Found whilst sanity-grepping: [here](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/653299c12a43671c5b8cb31ec159120490c8ac94/docs/dev-setup/linux.md?plain=1#L24) and[ here](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/653299c12a43671c5b8cb31ec159120490c8ac94/.github/workflows/test_lottie.yaml#L27) and a few references in `.dictionary` 🧹

**Comment by oskirby** [comment]
@bakulf I'm guessing this has never worked, because the `<allow_active>auth_admin</allow_active>` policy should have prompted the user with a password dialog when activating the VPN, and I don't think I have ever seen that behaviour out of the VPN client.

**Comment by oskirby** [comment]
Okay, I think I understand why the polkit code does nothing. The call `polkit_unix_process_new_for_owner(getpid(), 0, -1)` means that we are checking the permissions of the daemon (not the entity that invoked the D-Bus method). Because the daemon starts as root, this means that the `allow_admin` permission will always be met.

For this to have had any effect, instead of `getpid()` we should have been using the PID of the D-Bus method's caller.

**Comment by dreirund** [comment]
*[Side-Topic] for anyone interested: Some more context to this: https://www.openwall.com/lists/oss-security/2023/08/03/1.*

**Pull request merged**
