### PR TITLE
VPN-5759 - Remove "newOnboarding" feature flag and obsolete onboarding screens

### PR DESCRIPTION
**Pull request by brizental**

### CODE REVIEW

**Review by mcleinman — CHANGES_REQUESTED** [review]
The ticket starts with "Pending a successful rollout of the updated onboarding experience...". Given that this feature just made it to prod today, I would like to wait 2-3 weeks before merging this. There is no rush to remove this code, and if we need to do some sort of rollback it's going to be far more painful if we've removed it.

**Comment by brizental** [comment]
>  The ticket starts with "Pending a successful rollout of the updated onboarding experience...". Given that this feature just made it to prod today, I would like to wait 2-3 weeks before merging this. There is no rush to remove this code, and if we need to do some sort of rollback it's going to be far more painful if we've removed it.

Sure. This was initially an ask from product, but after raising this concern we have agreed to wait a month before merging this -- I have added a calendar reminder for now.

**Review by flodolo — APPROVED** [review]

**Comment by brizental** [comment]
@mcleinman Tomorrow is the merge date for this as discussed with Santiago. Let me know if you would like to give a new looks before we go ahead.

**Review by mcleinman — APPROVED** [review]
Looks awesome, thanks for this.

**Pull request merged**
