### PR TITLE
VPN-5544: Remove tutorials from the UI

### PR DESCRIPTION
**Pull request by MattLichtenstein**
## Description

- Refactor the tips and tricks UI to no longer display tutorials

https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/9c290019-4369-4a1a-9544-1fe83caad20a

## Reference

[VPN-5544: Remove tutorials from the UI](https://mozilla-hub.atlassian.net/browse/VPN-5544)

### CODE REVIEW

**Review by Gela — APPROVED** [review]

**Comment by vinocher** [comment]
Should the tutorials in the addons directory be removed? For example, addons\tutorial_01_get_started etc.

**Comment by vinocher** [comment]
Should the tutorials in the addons directory be removed? For example, addons\tutorial_01_get_started etc.

**Comment by vinocher** [comment]
Should nebula\ui\components\MZTutorialList.qml and reference to MZTutorial be removed?

**Review by Gela — APPROVED** [review]

**Comment by MattLichtenstein** [comment]
> Should the tutorials in the addons directory be removed? For example, addons\tutorial_01_get_started etc.

We'll need to leave these so that they remain present in future addon RC's because we want to continue shipping tutorials to older clients

> Should nebula\ui\components\MZTutorialList.qml and references to MZTutorial be removed?

Yes, though I intentionally left everything that wasn't critical to 
- removing access to tutorials by users
- getting CI to pass 

Due to where we are at in the release process, I wanted as little code churn as possible. There is a [ticket to rip everything else out](https://mozilla-hub.atlassian.net/browse/VPN-5545) at a future time when there is more opportunity to regression test. What are your thoughts on this? @vinocher

**Comment by vinocher** [comment]
> Due to where we are at in the release process, I wanted as little code churn as possible. There is a [ticket to rip everything else out](https://mozilla-hub.atlassian.net/browse/VPN-5545) at a future time when there is more opportunity to regression test. What are your thoughts on this? @vinocher

Sounds like a good plan. Thanks!

**Review by vinocher — APPROVED** [review]

**Pull request merged**
