### PR TITLE
Remove addon condition for testing

### PR DESCRIPTION
**Pull request by mcleinman**
## Description

QA requested removal of the timing condition to make testing easier: https://mozilla-hub.atlassian.net/browse/FXVPN-32?focusedCommentId=974354

I've included "adding this back in" in the ticket to finalize this addon: https://mozilla-hub.atlassian.net/browse/FXVPN-280

## Reference

https://mozilla-hub.atlassian.net/browse/FXVPN-32?focusedCommentId=974354

## Checklist
    
- [x] My code follows the style guidelines for this project
- [x] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [x] I have performed a self review of my own code
- [x] I have commented my code PARTICULARLY in hard to understand areas
- [x] I have added thorough tests where needed

### CODE REVIEW

**Comment by mcleinman** [comment]
The failing functional test is due to VPN-6778, and will be fixed by https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10123.

Adding `await vpn.setSetting('languageCode', 'fr');` to the start of the failing test allows it to pass. I believe it's safe to merge this. (Or we can wait for VPN-6778 to be merged in first.)

**Review by lesleyjanenorton — APPROVED** [review]
👍

Q: Is there a reason we need to add the timing condition back in or can we just change 'staging' to 'production' when we're ready to ship this?

**Comment by mcleinman** [comment]
> 👍
> 
> Q: Is there a reason we need to add the timing condition back in or can we just change 'staging' to 'production' when we're ready to ship this?

There is a product requirement to not show this message until people have been using the client for 2 weeks.

**Comment by mcleinman** [comment]
The one failing test is going to be fixed separately and is unrelated to this PR.

**Pull request merged**
