### PR TITLE
VPN-4706, VPN-4709 - Initialize Glean instance from the Android Daemon

### PR DESCRIPTION
**Pull request by brizental**
I have tested this with a sample ping from the daemon and it works i.e. it is able to submit pings and record metrics.

### CODE REVIEW

**Comment by brizental** [comment]
Ok, moving this back to draft just because Is till need to figure out how to sync up the gleanEnabled status between the main app and the daemon, oops.

**Review by brizental — COMMENTED** [review]
Follow up work: 

- https://mozilla-hub.atlassian.net/browse/VPN-4720
- I would also love to write tests for this. @strseb Do you think it will be possible to test this using the Android functional tests work that you are doing? Let me know and I'll file a ticket and block on your stuff :)

**Review by strseb — APPROVED** [review]

**Comment by strseb** [comment]
Re: Testing. 
Instead of using functional test's we can write instrumented test cases. The `daemon project` is already setup to run those :) 
https://developer.android.com/training/testing/instrumented-tests
https://developer.android.com/training/testing/other-components/services

**Comment by brizental** [comment]
> Instead of using functional test's we can write instrumented test cases. The daemon project is already setup to run those 

Nice. I'll write the tests in a follow-up just so I don't block this. https://mozilla-hub.atlassian.net/browse/VPN-4738

**Pull request merged**
