### PR TITLE
VPN-4712: add installation ID for iOS

### PR DESCRIPTION
**Pull request by mcleinman**
## Description

Android work will come in a separate PR.

To test, you likely want to add a debug tag (`Glean.shared.setDebugViewTag("VPNTest")`) after the two Glean initialization calls in Swift. Then, look at the pings [in Glean's tool](https://debug-ping-preview.firebaseapp.com/pings/VPNTest).

## Reference

https://mozilla-hub.atlassian.net/browse/VPN-4712
https://mozilla-hub.atlassian.net/wiki/spaces/SECPRV/pages/184419319/VPN+session+pings+-+Tech+spec

## Checklist
    
- [X] My code follows the style guidelines for this project
- [X] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [X] I have performed a self review of my own code
- [X] I have commented my code PARTICULARLY in hard to understand areas
- [X] I have added thorough tests where needed

### CODE REVIEW

**Comment by mcleinman** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

How many VPN sessions are started outside the app (in system settings, etc.)? This is the last variable needed to track this. 

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? 

We do not have great insight into some of basic questions about our users: Where do they activate the VPN from? How long are sessions?

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

Carefully considered which metrics were needed.

4) Can current instrumentation answer these questions?

No, unfortunately.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Name</td>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>installation_id</td>
    <td>A unique ID shared between the daemon and the main Glean instance, which remains the same as long as the app is installed (or the user allows data gathering). It's like a Client ID that is shared across both Glean instances.</td>
    <td>technical</td>
    <td><a href="https://mozilla-hub.atlassian.net/browse/VPN-4712">VPN-4712</a></td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/"

7) How long will this data be collected?  Choose one of the following:

* I want to permanently monitor this data. mcleinman@mozilla.com

8) What populations will you measure?

No filters - all channels, countries, and locales, unless the user has opted out of data collection on that device.

9) If this data collection is default on, what is the opt-out mechanism for users?

When launching the app for the first time, a user is given an option for whether to allow data collection. After this initial set up screen, a user can always toggle data collection permissions in the System Preferences screen.

10) Please provide a general description of how you will analyze this data.

Dashboards that product managers and others will consult on a regular basis.

11) Where do you intend to share the results of your analysis?

Within the Mozilla VPN team and Security and Privacy Products team.

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? 

No

**Comment by mcleinman** [comment]
Tagging @travis79 for data review. Unless testing results in significant changes, this is the final data review for this project. Thank you for all your help with this.

**Review by travis79 — APPROVED** [review]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
>     1. What questions will you answer with this data?
> 
> 
> How many VPN sessions are started outside the app (in system settings, etc.)? This is the last variable needed to track this.
> 
>     2. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
> We do not have great insight into some of basic questions about our users: Where do they activate the VPN from? How long are sessions?
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> Carefully considered which metrics were needed.
> 
>     4. Can current instrumentation answer these questions?
> 
> 
> No, unfortunately.
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> 
> **Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**
> Measurement Name 	Measurement Description 	Data Collection Category 	Tracking Bug #
> installation_id 	A unique ID shared between the daemon and the main Glean instance, which remains the same as long as the app is installed (or the user allows data gathering). It's like a Client ID that is shared across both Glean instances. 	technical 	[VPN-4712](https://mozilla-hub.atlassian.net/browse/VPN-4712)
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> This collection is documented in the Glean Dictionary at [dictionary.telemetry.mozilla.org](https://dictionary.telemetry.mozilla.org/)"
> 
>     7. How long will this data be collected?  Choose one of the following:
> 
> 
>     * I want to permanently monitor this data. [mcleinman@mozilla.com](mailto:mcleinman@mozilla.com)
> 
> 
>     8. What populations will you measure?
> 
> 
> No filters - all channels, countries, and locales, unless the user has opted out of data collection on that device.
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> When launching the app for the first time, a user is given an option for whether to allow data collection. After this initial set up screen, a user can always toggle data collection permissions in the System Preferences screen.
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
> Dashboards that product managers and others will consult on a regular basis.
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
> Within the Mozilla VPN team and Security and Privacy Products team.
> 
>     12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection?
> 
> 
> No

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/).

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, through the telemetry preferences in the application settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

Permanent collection to be monitored by mcleinman@mozilla.com

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1, technical data

5) Is the data collection request for default-on or default-off?

Default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

Yes, though it is technical only in nature and only related to the installation 

7) Is the data collection covered by the existing Firefox privacy notice?

Yes

8) Does the data collection use a third-party collection tool?

No

## Result

data-review+

**Review by brizental — COMMENTED** [review]
Did you check that the application id is different for daemon and main app? If it's the same this metric is unnecessary.

**Comment by mcleinman** [comment]
> Did you check that the application id is different for daemon and main app? If it's the same this metric is unnecessary.

Yes, confirmed in these two pings: [one](https://debug-ping-preview.firebaseapp.com/pings/MattVPN/fc7f9d8c-3c7d-4f1e-85e8-cf82d4b3ac57), [two](https://debug-ping-preview.firebaseapp.com/pings/MattVPN/c1468b50-5e03-4573-b58d-c429da879a03)

**Comment by brizental** [comment]
> Yes, confirmed in these two pings: [one](https://debug-ping-preview.firebaseapp.com/pings/MattVPN/fc7f9d8c-3c7d-4f1e-85e8-cf82d4b3ac57), [two](https://debug-ping-preview.firebaseapp.com/pings/MattVPN/c1468b50-5e03-4573-b58d-c429da879a03)

Ping two here doesn't contain the `metadata` field. What is the application id for that ping? This is important for us to figure out, because if indeed it is a different application id we also need to register that (see: https://mozilla.github.io/glean/book/user/adding-glean-to-your-project/enable-data-ingestion.html). Maybe it's not getting the `metadata` field because it's different and it's not going through the ingestion pipeline like the other ping... But still.

**Comment by mcleinman** [comment]
> > Yes, confirmed in these two pings: [one](https://debug-ping-preview.firebaseapp.com/pings/MattVPN/fc7f9d8c-3c7d-4f1e-85e8-cf82d4b3ac57), [two](https://debug-ping-preview.firebaseapp.com/pings/MattVPN/c1468b50-5e03-4573-b58d-c429da879a03)
> 
> Ping two here doesn't contain the `metadata` field. What is the application id for that ping? This is important for us to figure out, because if indeed it is a different application id we also need to register that (see: https://mozilla.github.io/glean/book/user/adding-glean-to-your-project/enable-data-ingestion.html). Maybe it's not getting the `metadata` field because it's different and it's not going through the ingestion pipeline like the other ping... But still.

Sorry, I misunderstood your initial request. I believe we need this field as long as the `client_id`s are different, which they are in this case. (At least, that is how the tech spec was written/approved.) Can you explain how an identical `application_id` would allow us to skip it?

That said, seems important to get the ingestion working. Filing a ticket for that.

**Comment by brizental** [comment]
> Sorry, I misunderstood your initial request. I believe we need this field as long as the client_ids are different, which they are in this case. (At least, that is how the tech spec was written/approved.) Can you explain how an identical application_id would allow us to skip it?

Ok, as I started writing the reply to this I realized I am wrong. Which is funny, because I thought exactly the same thing when I reviewed the proposal and had to convince me of the contrary. Anyways, ignore all this and sorry for fuss. We do need to check about the app id for registering though, so I guess not all is lost.

**Review by brizental — APPROVED** [review]

**Pull request merged**
