### PR TITLE
Remove unused environment variables from .taskcluster.yml

### PR DESCRIPTION
**Pull request by ahal**

### CODE REVIEW

**Comment by strseb** [comment]
I've added those back, as it seems the windows-generic-worker need them 😅

**Comment by ahal** [comment]
> @ahal I've added those back, as it seems the windows-generic-worker needs them 😅

Oh, weird.. Is it possible your branch wasn't based on top of the revision that removed them? Do you have a link to the error somewhere?

**Comment by strseb** [comment]
See https://firefox-ci-tc.services.mozilla.com/tasks/S_A87Za5ROWmm297BvksUQ/runs/0/logs/public/logs/live.log

**Comment by ahal** [comment]
Ah, that's good since we fixed that in a newer version of Taskgraph. I'll bump the version of Taskgraph being used in this PR as well and then that error won't happen anymore :)

**Comment by ahal** [comment]
Lol, and sorry.. I totally didn't even realize the Decision task failed ><

**Comment by ahal** [comment]
Ok that should fix it.

**Review by strseb — APPROVED** [review]

**Pull request merged**
