### PR TITLE
Ring animation shader

### PR DESCRIPTION
**Pull request by flozia**
This replaces the current ring animation that is using a `QML canvas` with a `shader effect`. Until now I was just able to test the shader on my machine and I’m not confident about the consistency of the performance improvements and the appearance across all platforms and devices.

### Animation
| Before | After |
| --- | --- |
| vpn-ring-canvas | vpn-ring-shader |

### CPU usage
**How I tested**
1. Turned-on VPN
2. Monitored CPU usage using `top`

**Where I tested**
| Device | OS | Processor | Memory | Graphics |
| --- | --- | --- | --- | --- |
| MacBook Pro (13-inch, 2019) | macOS Big Sur | 2,8 GHz Quad-Core Intel Core i7 | 16 GB 2133 MHz LPDDR3 | Intel Iris Plus Graphics 655 1536 MB |

**Results**
| No animation | Before (QML Canvas) | After (Shader effect) |
| --- | --- | --- |
|  vpn-cpu-rings-removed | vpn-cpu-rings-canvas | vpn-cpu-rings-shader |

### CODE REVIEW

**Comment by oskirby** [comment]
I gave this a quick test on Linux, and it seems that the shader doesn't compile successfully, and gives the following output on each tick of the render loop:
```
[12.08.2021 09:42:39.967] Warning: shader compilation failed: 
"0:2(12): warning: extension `GL_ARB_fragment_coord_conventions' unsupported in fragment shader\n0:6(20): error: No precision specified in this scope for type `float'\n0:6(36): error: No precision specified in this scope for type `float'\n0:6(8): error: No precision specified in this scope for type `float'\n0:7(2): error: No precision specified in this scope for type `float'\n0:12(21): error: No precision specified in this scope for type `float'\n0:12(37): error: No precision specified in this scope for type `float'\n0:12(56): error: No precision specified in this scope for type `float'\n0:12(8): error: No precision specified in this scope for type `float'\n0:13(2): error: No precision specified in this scope for type `float'\n0:14(2): error: No precision specified in this scope for type `float'\n0:19(25): error: No precision specified in this scope for type `float'\n0:19(42): error: No precision specified in this scope for type `float'\n0:19(59): error: No precision specified in this scope for type `float'\n0:19(80): error: No precision specified in this scope for type `float'\n0:19(8): error: No precision specified in this scope for type `float'\n0:25(2): error: No precision specified in this scope for type `vec2'\n0:26(2): error: No precision specified in this scope for type `float'\n0:29(2): error: No precision specified in this scope for type `float'\n0:30(2): error: No precision specified in this scope for type `float'\n0:31(2): error: No precision specified in this scope for type `float'\n0:32(2): error: No precision specified in this scope for type `vec4'\n0:35(2): error: No precision specified in this scope for type `float'\n0:36(2): error: No precision specified in this scope for type `float'\n0:38(2): error: No precision specified in this scope for type `float'\n0:39(2): error: No precision specified in this scope for type `float'\n0:41(2): error: No precision specified in this scope for type `float'\n0:42(2): error: No precision specified in this scope for type `float'\n0:45(2): error: No precision specified in this scope for type `float'\n0:46(2): error: No precision specified in this scope for type `float'\n0:47(2): error: No precision specified in this scope for type `float'\n0:48(2): error: No precision specified in this scope for type `float'\n0:51(2): error: No precision specified in this scope for type `float'\n"
[12.08.2021 09:42:39.968] Warning: QOpenGLShader::link: error: program lacks a fragment shader

[12.08.2021 09:42:39.992] Warning: QOpenGLShader::compile(Fragment): 0:2(12): warning: extension `GL_ARB_fragment_coord_conventions' unsupported in fragment shader
0:6(20): error: No precision specified in this scope for type `float'
0:6(36): error: No precision specified in this scope for type `float'
0:6(8): error: No precision specified in this scope for type `float'
0:7(2): error: No precision specified in this scope for type `float'
0:12(21): error: No precision specified in this scope for type `float'
0:12(37): error: No precision specified in this scope for type `float'
0:12(56): error: No precision specified in this scope for type `float'
0:12(8): error: No precision specified in this scope for type `float'
0:13(2): error: No precision specified in this scope for type `float'
0:14(2): error: No precision specified in this scope for type `float'
0:19(25): error: No precision specified in this scope for type `float'
0:19(42): error: No precision specified in this scope for type `float'
0:19(59): error: No precision specified in this scope for type `float'
0:19(80): error: No precision specified in this scope for type `float'
0:19(8): error: No precision specified in this scope for type `float'
0:25(2): error: No precision specified in this scope for type `vec2'
0:26(2): error: No precision specified in this scope for type `float'
0:29(2): error: No precision specified in this scope for type `float'
0:30(2): error: No precision specified in this scope for type `float'
0:31(2): error: No precision specified in this scope for type `float'
0:32(2): error: No precision specified in this scope for type `vec4'
0:35(2): error: No precision specified in this scope for type `float'
0:36(2): error: No precision specified in this scope for type `float'
0:38(2): error: No precision specified in this scope for type `float'
0:39(2): error: No precision specified in this scope for type `float'
0:41(2): error: No precision specified in this scope for type `float'
0:42(2): error: No precision specified in this scope for type `float'
0:45(2): error: No precision specified in this scope for type `float'
0:46(2): error: No precision specified in this scope for type `float'
0:47(2): error: No precision specified in this scope for type `float'
0:48(2): error: No precision specified in this scope for type `float'
0:51(2): error: No precision specified in this scope for type `float'

[12.08.2021 09:42:39.992] Warning: *** Problematic Fragment shader source code ***
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#ifndef GL_FRAGMENT_PRECISION_HIGH
#define highp mediump
#endif
#line 1

        varying mediump vec2 qt_TexCoord0;
        uniform lowp float qt_Opacity;
        uniform lowp float animationProgress;

        float draw_circle(float distance, float radius) {
            float antialias = 0.005;

            return smoothstep(radius, radius - antialias, distance);
        }

        float compose_ring(float distance, float strokeWidth, float radius) {
            float circle1 = draw_circle(distance, radius);
            float circle2 = draw_circle(distance, radius - strokeWidth);

            return circle1 - circle2;
        }

        float calc_ring_radius(float minRadius, float maxRadius, float currentRadius, float offset) {
            return mod(maxRadius * offset + currentRadius, maxRadius) + minRadius;
        }

        void main() {
            // Center coordinate
            vec2 center = vec2(0.5, 0.275);
            float centerDistance = length(qt_TexCoord0 - center);

            // Ring properties
            float strokeWidth = 0.015;
            float minRadius = 0.0;
            float maxRadius = 0.5;
            vec4 color = vec4(1.0, 1.0, 1.0, 1.0);

            // Rings
            float ringRadius1 = calc_ring_radius(minRadius, maxRadius, animationProgress, 0.0);
            float ring1 = compose_ring(centerDistance, strokeWidth, ringRadius1);

            float ringRadius2 = calc_ring_radius(minRadius, maxRadius, animationProgress, 0.33);
            float ring2 = compose_ring(centerDistance, strokeWidth, ringRadius2);

            float ringRadius3 = calc_ring_radius(minRadius, maxRadius, animationProgress, 0.66);
            float ring3 = compose_ring(centerDistance, strokeWidth, ringRadius3);

            // Radial gradient
            float gradientWidth = 5.0;
            float gradientBlur = 0.8;
            float gradientOffset = 0.28;
            float gradientMask = 1.0 - max(0.0, 0.25 - pow(max(0.0, abs(centerDistance - gradientOffset) * gradientWidth), gradientWidth * gradientBlur));

            // Output rings
            float rings = ring1 + ring2 + ring3;
            gl_FragColor = color * rings - gradientMask;
        }
```

**Comment by flozia** [comment]
Thank you @oskirby for giving this a try. My latest commit might solve the error:

```
No precision specified in this scope for type `float'
```

I’m not sure about the other warnings and have to investigate them further.

**Comment by bakulf** [comment]
It works for me! Nice! well done.

**Comment by bakulf** [comment]
@oskirby do you see other issues? Or we can land it?

**Review by bakulf — APPROVED** [review]

**Comment by oskirby** [comment]
Yep, that works great for me now, and it came with a drop in CPU load from about 15% to 7% on my machine (Lenovo X1 Carbon / i7-8650U quad core).

**Review by oskirby — APPROVED** [review]

**Pull request merged**
