### PR TITLE
VPN-4018 - Do not get latest submodule version on Windows CI

### PR DESCRIPTION
**Pull request by brizental**
We should remove this `--remote` everywhere else it is used.

### CODE REVIEW

**Comment by strseb** [comment]
Curious if this works. TC also checks out submodules, hopefully it does not do remote 🤞

**Review by strseb — APPROVED** [review]

**Comment by oskirby** [comment]
I think we might want to add `--remote` back for the `i18n` submodule. We are kind of relying on that to ensure we have updated strings in the absence of any kind of process for keeping the submodule current.

**Comment by brizental** [comment]
> I think we might want to add --remote back for the i18n submodule. We are kind of relying on that to ensure we have updated strings in the absence of any kind of process for keeping the submodule current.

Good to know. Is there already a ticket for creating a process for this though? Happy to file one otherwise.

**Comment by oskirby** [comment]
> Done and good to know. Is there already a ticket for creating a process for this though? Happy to file one otherwise.

I think the last time we got bitten by a submodule issue, we filed #5240 ([VPN-3507](https://mozilla-hub.atlassian.net/browse/VPN-3507)) to capture our thoughts on the matter.

**Review by oskirby — APPROVED** [review]

**Pull request merged**
