### PR TITLE
VPN-6469 and VPN-6470: Addon messages for v2.24

### PR DESCRIPTION
**Pull request by mcleinman**
## Description

What's new and update messages for v2.24

## Reference

VPN-6469 and VPN-6470

## Checklist
    
- [x] My code follows the style guidelines for this project
- [x] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [x] I have performed a self review of my own code
- [x] I have commented my code PARTICULARLY in hard to understand areas
- [x] I have added thorough tests where needed

### CODE REVIEW

**Review by oskirby — APPROVED** [review]
LGTM

**Comment by flodolo** [comment]
A couple of questions:
* Who can help to confirm that the content matches expectations? IIRC for both last versions we had issues, which resulted in strings being exposed twice, but I have no way to tell.
* Can https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8368 be put on the radar? If these strings used a variable for the version number, and we had the ability to share strings among addons, these wouldn't need any additional time for translation.

**Comment by mcleinman** [comment]
> A couple of questions:
> 
>     * Who can help to confirm that the content matches expectations? IIRC for both last versions we had issues, which resulted in strings being exposed twice, but I have no way to tell.
> 
>     * Can [Implement ability to reuse strings in addons  #8368](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8368) be put on the radar? If these strings used a variable for the version number, and we had the ability to share strings among addons, these wouldn't need any additional time for translation.

Asking Santiago for a double check on those strings.

And the addon issue is being worked on in the next sprint. Thanks for the continued advocacy of it - now that the dust has mostly settled, it makes sense to prioritize it.

**Comment by mcleinman** [comment]
Santiago confirmed these strings via DM

**Pull request merged**
