### PR TITLE
VPN-4881: Fix 2.16 update message for old windows clients

### PR DESCRIPTION
**Pull request by MattLichtenstein**
## Description

- Update strings for 2.16 update message for Windows clients on 2.10-2.12 who need to upgrade via web

## Reference

[VPN-4881: Implement 'What's New' and 'Update' message for 2.16](https://mozilla-hub.atlassian.net/browse/VPN-4881)

### CODE REVIEW

**Review by brizental — APPROVED** [review]

**Comment by MattLichtenstein** [comment]
@flodolo fyi this is going to require translations

**Comment by flodolo** [comment]
> @flodolo fyi this is going to require translations

How? This string is not changing the manifest, which is the only thing exposed to localization (and that's why I wasn't pinged for review).

**Comment by flodolo** [comment]
AFAIK, you need to update this and use a new ID in the process
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/addons/message_update_v2.16/manifest.json#L56-L58

**Comment by MattLichtenstein** [comment]
@flodolo the JS function conditionally replaces strings in the manifest. I saw translations for the old strings [here](https://pontoon.mozilla.org/nl/mozilla-vpn-client/addons/message_update_v2.16/strings.xliff/?string=281190)

**Comment by flodolo** [comment]
> @flodolo the JS function conditionally replaces strings in the manifest. I saw a translation for one of the old strings [here](https://pontoon.mozilla.org/nl/mozilla-vpn-client/addons/message_update_v2.16/strings.xliff/?string=281190)

And those are extracted from the manifest file. What I'm saying is that the change in this PR won't show up for localization at any point, unless I'm very wrong in my understanding of the scripts extracting strings for addons.

**Comment by MattLichtenstein** [comment]
@flodolo I've updated the manifest id's and text - these should be marked for localization now, right?

**Review by flodolo — APPROVED** [review]
Yes, now it will show up for localization.

**Pull request merged**
