### PR TITLE
VPN-4065: update connection health metrics

### PR DESCRIPTION
**Pull request by mcleinman**
## Description

Three things:
- **One major change (that means we won't be able to compare connection health metrics before and after this point):** We used to record the connection health event metrics when the connection health *changed* status. We now will record it on every connection health check, as the ratio of stable-to-bad events is important to our analysis. This may be a controversial thing - feel free to push back on this update.
- Add two existing connection health metrics to the `vpnsession` ping.
- Create a new metric for when connection health checks are positive. (This metric is only on the `vpnsession` ping.)

## Reference

https://mozilla-hub.atlassian.net/browse/VPN-4065

## Checklist
    
- [X] My code follows the style guidelines for this project
- [X] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [X] I have performed a self review of my own code
- [X] I have commented my code PARTICULARLY in hard to understand areas
- [X] I have added thorough tests where needed

### CODE REVIEW

**Comment by mcleinman** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

This form is only for `connection_health_stable`, as it is the only new metric in this PR.

1) What questions will you answer with this data?

How often do connection health checks come back positive? 

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? 

We previously recorded bad outcomes from connection health check, but have no data on how often these bad outcomes exist relative to all connection health checks. This allows us to better analyze the network health and user experience.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

Carefully considered which metrics were needed. 

We can't use total connection time, as the connection health metric only runs on mobile apps when the apps are foregrounded. Thus, we need this positive connection health event to be able to create a ratio of bad-to-all-connection-health-checks.

4) Can current instrumentation answer these questions?

No, unfortunately.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Name</td>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>connection_health_stable</td>
    <td>An event that registers successful connection health checks.</td>
    <td>technical</td>
    <td>https://mozilla-hub.atlassian.net/browse/VPN-4065</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/"

7) How long will this data be collected?  Choose one of the following:

* I want to permanently monitor this data. mcleinman@mozilla.com

8) What populations will you measure?

No filters - all channels, countries, and locales, unless the user has opted out of data collection on that device.

9) If this data collection is default on, what is the opt-out mechanism for users?

When launching the app for the first time, a user is given an option for whether to allow data collection. After this initial set up screen, a user can always toggle data collection permissions in the System Preferences screen.

10) Please provide a general description of how you will analyze this data.

Dashboards that product managers and others will consult on a regular basis.

11) Where do you intend to share the results of your analysis?

Within the Mozilla VPN team and Security and Privacy Products team.

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? 

No

**Comment by mcleinman** [comment]
Adding @travis79 for data review. Thanks!

**Review by bakulf — APPROVED** [review]

**Review by brizental — CHANGES_REQUESTED** [review]
Please add unit tests for the new collection, if possible.

**Comment by mcleinman** [comment]
> Please add unit tests for the new collection, if possible.

No existing tests exist for this work, per discussion I created a ticket for future work: https://mozilla-hub.atlassian.net/browse/VPN-4454

**Review by brizental — APPROVED** [review]

**Review by travis79 — APPROVED** [review]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
> This form is only for `connection_health_stable`, as it is the only new metric in this PR.
> 
>     1. What questions will you answer with this data?
> 
> 
> How often do connection health checks come back positive?
> 
>     2. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
> We previously recorded bad outcomes from connection health check, but have no data on how often these bad outcomes exist relative to all connection health checks. This allows us to better analyze the network health and user experience.
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> Carefully considered which metrics were needed.
> 
> We can't use total connection time, as the connection health metric only runs on mobile apps when the apps are foregrounded. Thus, we need this positive connection health event to be able to create a ratio of bad-to-all-connection-health-checks.
> 
>     4. Can current instrumentation answer these questions?
> 
> 
> No, unfortunately.
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> 
> **Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**
> Measurement Name 	Measurement Description 	Data Collection Category 	Tracking Bug #
> connection_health_stable 	An event that registers successful connection health checks. 	technical 	https://mozilla-hub.atlassian.net/browse/VPN-4065
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> This collection is documented in the Glean Dictionary at [dictionary.telemetry.mozilla.org](https://dictionary.telemetry.mozilla.org/)"
> 
>     7. How long will this data be collected?  Choose one of the following:
> 
> 
>     * I want to permanently monitor this data. [mcleinman@mozilla.com](mailto:mcleinman@mozilla.com)
> 
> 
>     8. What populations will you measure?
> 
> 
> No filters - all channels, countries, and locales, unless the user has opted out of data collection on that device.
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> When launching the app for the first time, a user is given an option for whether to allow data collection. After this initial set up screen, a user can always toggle data collection permissions in the System Preferences screen.
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
> Dashboards that product managers and others will consult on a regular basis.
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
> Within the Mozilla VPN team and Security and Privacy Products team.
> 
>     12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection?
> 
> 
> No

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/).

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, through the data preferences in the application settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

Permanent collection to be monitored over time by [mcleinman@mozilla.com](mailto:mcleinman@mozilla.com)

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1, Technical data

5) Is the data collection request for default-on or default-off?

Default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No

7) Is the data collection covered by the existing Firefox privacy notice?

Yes

8) Does the data collection use a third-party collection tool?

No

## Result

data-review+

**Pull request merged**
