### PR TITLE
Linux improved desktop file search

### PR DESCRIPTION
**Pull request by Cimbali**
## Description

Improve the search for desktop files on Linux by following freedesktop specs closer

- correct user directories (from `$XDG_DATA_HOME` if defined before `$HOME/local/data`) 
- correct system fallbacks (both `/usr/locale/share/applications` and `/use/share/applications`)
- added missing desktop-file hiding mechanisms `OnlyShowIn`, `NotShowIn`, and `Hidden`
- added autostart desktop files to cover applications started at launch (because autostart is implemented by copied desktop files which means they are referenced as different application “ids”)

## Reference

None

## Checklist
    
- [x] My code follows the style guidelines for this project
- [x] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [x] I have performed a self review of my own code
- [x] I have commented my code PARTICULARLY in hard to understand areas
- [x] I have added thorough tests where needed

### CODE REVIEW

**Review by oskirby — APPROVED** [review]
This looks great!

**Comment by Cimbali** [comment]
Actually [desktop file ids](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html#desktop-file-id) in the spec are only the basenames of the desktop files, and conflicting files in different directories should appear as a single application. Looking at auto-start desktop files only makes sense if we keep the full paths as ids. This has the drawback of generating more duplicate entries.

I could change the PR to use basenames instead.

**Comment by Cimbali** [comment]
Small oversight: desktop files are allowed to be in subdirectories too.

This still currently duplicates (some) applications by using full paths as ids.

**Comment by oskirby** [comment]
> Actually [desktop file ids](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html#desktop-file-id) in the spec are only the basenames of the desktop files, and conflicting files in different directories should appear as a single application. Looking at auto-start desktop files only makes sense if we keep the full paths as ids. This has the drawback of generating more duplicate entries.
> 
> I could change the PR to use basenames instead.

I like the idea of using the basename/desktop ID instead, that seems like the more correct approach and it probably cleans things up and removes ambiguity in the daemon. However, I would argue that we should tackle that in another PR.

**Comment by Cimbali** [comment]
Thanks @oskirby. I’ve put the desktop ID stuff in PR #6782

**Pull request merged**
