### PR TITLE
Fix #1741

### LINKED ISSUE #1741: Top part of the VPN Client simulator (WASM) is hidden
Something changed, causing the content to move and hide behind the `Viewer Menu`. It's visible in the starting screen, but also in the main one (the cog to access preferences is hidden).
https://mozilla-mobile.github.io/mozilla-vpn-client/

Schermata 2021-09-07 alle 07 22 36

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-957)

### LINKED ISSUE #1749: Screen cut off iOS - top menu bar can't navigate back to main screen
iPhone XR iOS 14.7.1

Downloaded and installed the latest Test flight for v2.5 this morning and after signing in and the app loaded I was greeted with a cut off screen at the top -- see images:
 !Image from iOS (1).png|thumbnail!  !Image from iOS (1).png|thumbnail! 

Seems like the padding or something is being lost from the top down?
Either way I couldn't then navigate back to the main screen after drilling down into the location/server selection screen because the back arrow was not working when overlapping with the main phone top menu area.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-961)

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
Fixes #1741 
Screen Shot 2021-09-07 at 10 18 08 AM

This may also fix #1749

### CODE REVIEW

**Comment by mbirghan** [comment]
This kind of fixes the issue for iOS but creates a different one 
image

**Comment by lesleyjanenorton** [comment]
@mbirghan whoops! thanks! Should be transparent again now.

**Comment by mbirghan** [comment]
Looks good on iOS now!

**Comment by lesleyjanenorton** [comment]
@mbirghan thank you!

**Review by bakulf — APPROVED** [review]

**Pull request merged**
