### PR TITLE
ci(taskcluster): make sure Android build failures turn the task red (…

### PR DESCRIPTION
**Pull request by ahal**
…#3413)

We noticed that sometimes the Android builds fail but the task is still
green. Partly this is taskcluster/taskcluster#4590 as the task should
fail if one of its declared artifacts doesn't exist.

But partly the build script itself should fail the task if one of its
commands returns non-zero. This PR fixes that by enabling `set -e` in
all the build scripts.

### CODE REVIEW

**Comment by ahal** [comment]
There's a chance this may introduce build failures if there are commands that are expected to return non-zero.. So there may be some follow-up work to fix those...

**Comment by ahal** [comment]
Also the Android builds are currently intermittently failing.. So this *will* appear to introduce regressions there, but really it's just making the failures visible.

**Comment by ahal** [comment]
Looks like the `wasm` builds were also failing.

**Review by strseb — APPROVED** [review]

**Review by mbirghan — APPROVED** [review]

**Comment by ahal** [comment]
Looks like the `wasm` task was also potentially failing?
https://firefox-ci-tc.services.mozilla.com/tasks/cvvWz1VBRhyF3w7X8yeUfA/runs/0/logs/public/logs/live.log

Or maybe the same OOM error the Androind ones are hitting?

**Comment by ahal** [comment]
@strseb I'll leave it up to you whether you want to merge this now or block on fixing the Android / wasm builds first.

**Pull request merged**
