### PR TITLE
VPN-5499: Remove unimplemented content from 2.17 messaging

### PR DESCRIPTION
**Pull request by MattLichtenstein**
## Description

    Describe your changes

## Reference

[VPN-5499: Remove unimplemented changes from 2.17 Update / What's new messages](https://mozilla-hub.atlassian.net/browse/VPN-5499)

### CODE REVIEW

**Comment by flodolo** [comment]
This is really unfortunate, because we have already started translating this content, so we're going to throw away work from the community. Also, this change is happening after the expected string freeze.

How can we avoid repeating this going forward?

**Review by brizental — APPROVED** [review]

**Comment by brizental** [comment]
> How can we avoid repeating this going forward?

If we see this is as a useful pattern going forward we could potentially implement a flag that prevent strings from getting extracted until we are sure they will make it into the release? Feels like overkill and like we should just _not_ do this going forward, but just in case.

**Comment by flodolo** [comment]
> we could potentially implement a flag that prevent strings from getting extracted

Don't we already have that?

> "translatable": false

**Comment by brizental** [comment]
> Don't we already have that?

Ah! 🤦‍♀️

**Review by flodolo — APPROVED** [review]
Please coordinate with content and make sure we use the exact same phrasing for the 2.18 update, if we end up including these features. That way, we can at least recover something from translation memories.

**Comment by MattLichtenstein** [comment]
> This is really unfortunate, because we have already started translating this content, so we're going to throw away work from the community. Also, this change is happening after the expected string freeze.

This was the plan all along, but we hand't considered the wasteful community contributions. We are experimenting with our release process in a way that puts our feature/fix freeze and string freeze on the same day, therefore it wasn't known what features would make it into the release so we "over-prepared" (by an unreasonable margin at that... since most of those features are unstarted/nowhere near completion) with the message content, knowing we would have to take some of the strings out. 

> Please coordinate with content and make sure we use the exact same phrasing for the 2.18 update, if we end up including these features. That way, we can at least recover something from translation memories.

This is the current plan - are there any other downsides to this?

**Comment by flodolo** [comment]
@MattLichtenstein 
Yet another problem of this approach :-( 

We need this fix on the release branch
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/releases/2.17.0/addons/message_whats_new_v2.17/manifest.json

**Comment by MattLichtenstein** [comment]
> @MattLichtenstein 
> 
> Yet another problem of this approach :-( 
> 
> 
> 
> We need this fix on the release branch
> 
> https://github.com/mozilla-mobile/mozilla-vpn-client/blob/releases/2.17.0/addons/message_whats_new_v2.17/manifest.json

This is fine, since we build addons from the main branch.

**Comment by flodolo** [comment]
> > @MattLichtenstein
> > Yet another problem of this approach :-(
> > We need this fix on the release branch
> > https://github.com/mozilla-mobile/mozilla-vpn-client/blob/releases/2.17.0/addons/message_whats_new_v2.17/manifest.json
> 
> This is fine, since we build addons from the main branch.

That's not the problem: localization extracts strings from all the branches, which means these strings that are not used are still being translated, until we removed them from all release branches.

**Pull request merged**
