### PR TITLE
Improve readme for functional tests and macOS cmake

### PR DESCRIPTION
**Pull request by mcleinman**
## Description

Move dummy build info to the top of section. Make .env file more explict.

Fix numbering of macOS cmake, and explain a possible error.

## Reference
https://mozilla-hub.atlassian.net/browse/VPN-3477

## Checklist
    
- [X] My code follows the style guidelines for this project
- [X] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [X] I have performed a self review of my own code
- [X] I have commented my code PARTICULARLY in hard to understand areas
- [X] I have added thorough tests where needed

### CODE REVIEW

**Review by mozrokafor — APPROVED** [review]

**Comment by bakulf** [comment]
Correct. We should be able to track commits and the corresponding Jira issues.

**Comment by mcleinman** [comment]
> Correct. We should be able to track commits and the corresponding Jira issues.

Jira ticket has been created: https://mozilla-hub.atlassian.net/browse/VPN-3477

Also adding a little tweak to macOS cmake instructions to this (encouraged by @brizental, thanks!).

**Comment by oskirby** [comment]
The changes related to functional testing are a bit stale after the changes in #5041 could you update the value of `MVPN_BIN` accordingly?

**Comment by mcleinman** [comment]
> The changes related to functional testing are a bit stale after the changes in #5041 could you update the value of `MVPN_BIN` accordingly?

Good catch, thanks. Done! (I think I got everything important.)

**Review by Gela — APPROVED** [review]
Awesome, thanks for doing this

**Pull request merged**
