### PR TITLE
try to fix qml imports

### PR DESCRIPTION
**Pull request by strseb**
## Description

i do think setting the policy to OLD broke things, my bad 🙏 . 
```
qt_policy(SET QTP0001 NEW)
```

-> So let's keep it at new and backport the changes of this policy to 6.2.4
->Set the resource prefix `/qt/qml`, it's the default value after 6.5
-> Add `/qt/qml` to the path by default.

This seems to fix everything on Windows (6.2.4/6.6.0) tested.

### CODE REVIEW

**Comment by brizental** [comment]
We should undo the NO_PLUGIN_OPTIONAL thing I did before if this is the fix.

**Review by lesleyjanenorton — APPROVED** [review]
worksonmymachine-1 


Do we still need the NO_PLUGIN_OPTIONAL change from #9531 ?

**Comment by mcleinman** [comment]
This works for me on Android for 6.6

**Comment by oskirby** [comment]
Works for my MacOS machine (tested both Qt 6.2.4 and Qt 6.6.3).

**Review by oskirby — APPROVED** [review]
As a thought for some future cleanup - we don't really need to use the path so prominently and in many cases we can load QML objects by type rather than URL.

For example, a `StackView::push()` can accept an `Item`, `Component` or `url` so in theory something like `stackView.push(ViewAboutUs{..})` should work too.

But that's too much work for now. Let's merge this and get the breakage fixed.

**Pull request merged**
