### PR TITLE
ci: re-enable Linux signing tasks

### PR DESCRIPTION
**Pull request by ahal**
## Description

Re-enable Linux signing tasks without using the production key.

### CODE REVIEW

**Review by strseb — APPROVED** [review]

**Comment by oskirby** [comment]
I can confirm that this produces signed source bundles, but I am struggling to verify that signature as I have no idea which public key to verify it against.

**Comment by ahal** [comment]
@oskirby the public key should be attached to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1776071)

**Comment by birdsarah** [comment]
Per decision in Feb retro, closing as more than 2 weeks without activity. You can re-open whenever.

**Comment by strseb** [comment]
@ahal - Sorry for the ping, but what would be needed to get this green? Can we help? :)

**Comment by ahal** [comment]
Actually, we might want to close this and remove any references to the Linux signing tasks :)

The reason is that these signing tasks were a launchpad thing and I don't think they'll be necessary once we switch over to Google Artifact Registry. We made the decision to not bother working on launchpad automation as a result.

**Comment by strseb** [comment]
Tbf @oskirby and I just had a conversation yesterday, that it might be nice beetmoving a signed source bundle onto archive. 
We have a few bugs of maintainers that have issues building - as the source bundle github Publishes does not contain any third party code so people have to fetch that all themselves to build packages. 
So if we had a central place to get the same complete source bundle have been using to build the released client, that could be neat. If that also would be signed by Mozilla, that would be extra neat. 
If that is too much hassle to get working - no worries :)

**Comment by ahal** [comment]
Ah ok, we could re-visit this then! I think the PR was mostly done (unless it's bitrotted again) and just needed testing.. Though I think the subkey that was being used to sign them might be expired now (I had told secops not to bother rotating it).. so I guess that might be a bit of a pain.

Though I guess I'm wondering what benefit signing would provide over just providing a hash or similar, as my understanding is that the signing was just a launchpad thing.

**Pull request closed without merging**
